# **Eigenvalues and Eigenvectors**
In linear algebra, an eigenvector of a square matrix
𝐴
 is a nonzero vector
𝑣
 that only changes by a scalar factor when the matrix is applied to it. The scalar factor is called the eigenvalue
𝜆.

Mathematically, this is expressed as:

𝐴
𝑣
=
𝜆
𝑣

where:

𝐴
A is an
𝑛
×
𝑛
 matrix,
𝑣
 is an eigenvector (a nonzero column vector), and
𝜆
is the corresponding eigenvalue (a scalar).


In [ ]:
import numpy as np

# Define a simple matrix
A = np.array([[2, 0],
              [0, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np

# Define a simple 2x2 matrix
A = np.array([[4, -2],
              [1, 1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display results
print("Original Matrix A:\n", A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)





Original Matrix A:
 [[ 4 -2]
 [ 1  1]]

Eigenvalues:
 [3. 2.]

Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
import numpy as np

# Define matrix
A = np.array([[4, -2], [1, 1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Convert first eigenvector to integer form
eigenvectors_scaled = eigenvectors / np.min(np.abs(eigenvectors), axis=0)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors (original):\n", eigenvectors)
print("Eigenvectors (scaled to integers):\n", np.round(eigenvectors_scaled))


Eigenvalues:
 [3. 2.]
Eigenvectors (original):
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
Eigenvectors (scaled to integers):
 [[2. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

# Define a 2x2 matrix
A = np.array([[4, 2],
              [1, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
B = np.array([[5, -2, 2],
              [-2, 8, 4],
              [2, 4, 7]])

eigenvalues, eigenvectors = np.linalg.eig(B)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [ 1.30839243  7.15491213 11.53669544]
Eigenvectors:
 [[-0.60772636 -0.79351536 -0.03165517]
 [-0.53335545  0.37829675  0.75658676]
 [ 0.58838816 -0.47668118  0.65312665]]
