In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.




[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# Example Matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

# Matrix Multiplication
def matrix_multiplication(A, B):
    return np.dot(A, B)

# Matrix Transpose
def matrix_transpose(A):
    return A.T

# Matrix Inverse
def matrix_inverse(A):
    if np.linalg.det(A) == 0:
        return "Matrix is singular and cannot be inverted"
    else:
        return np.linalg.inv(A)

# Identity Matrix
def identity_matrix(size):
    return np.eye(size)

# Diagonal Matrix
def diagonal_matrix(diagonal_elements):
    return np.diag(diagonal_elements)

# Symmetric Matrix
def symmetric_matrix(A):
    return (A + A.T) / 2

# Demonstrations
print("Matrix A:\n", A)
print("Matrix B:\n", B)

print("Matrix Multiplication of A and B:\n", matrix_multiplication(A, B))
print("Transpose of Matrix A:\n", matrix_transpose(A))
print("Inverse of Matrix A:\n", matrix_inverse(A))
print("Identity Matrix of size 2:\n", identity_matrix(2))
print("Diagonal Matrix from [1, 2, 3]:\n", diagonal_matrix([1, 2, 3]))
print("Symmetric Matrix from A:\n", symmetric_matrix(A))


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[2 0]
 [1 2]]
Matrix Multiplication of A and B:
 [[ 4  4]
 [10  8]]
Transpose of Matrix A:
 [[1 3]
 [2 4]]
Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Identity Matrix of size 2:
 [[1. 0.]
 [0. 1.]]
Diagonal Matrix from [1, 2, 3]:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Symmetric Matrix from A:
 [[1.  2.5]
 [2.5 4. ]]
