# **Vector** **Representation**
We can represent vactor by using python library name Numpy array

In [ ]:
# create a vector
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


# **Vector Arithmetic**
In this section will demonstrate simple vector-vector arithmetic, where all operations are performed element-wise between two vectors of equal length to result in a new vector with the same length

# Vector Addition
Two vectors of equal length can be added together to create a new third vector.

c = a + b

The new vector has the same length as the other two vectors. Each element of the new vector is calculated as the addition of the elements of the other vectors at the same index; for example:

a + b = (a1 + b1, a2 + b2, a3 + b3)

Or, put another way:

c[0] = a[0] + b[0]

c[1] = a[1] + b[1]

c[2] = a[2] + b[2]

We can add vectors directly in Python by adding NumPy arrays.

In [ ]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


# Vector Subtraction
One vector can be subtracted from another vector of equal length to create a new third vector.

c = a - b

As with addition, the new vector has the same length as the parent vectors and each element of the new vector is calculated as the subtraction of the elements at the same indices.

a - b = (a1 - b1, a2 - b2, a3 - b3)

Or, put another way:

c[0] = a[0] - b[0]

c[1] = a[1] - b[1]

c[2] = a[2] - b[2]

The NumPy arrays can be directly subtracted in Python.

In [ ]:
# subtract vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([0.5, 0.5, 0.5])
print(b)
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


# Vector Multiplication
Two vectors of equal length can be multiplied together.

c = a * b

As with addition and subtraction, this operation is performed element-wise to result in a new vector of the same length.

a * b = (a1 * b1, a2 * b2, a3 * b3)
or

ab = (a1b1, a2b2, a3b3)

Or, put another way:

c[0] = a[0] * b[0]

c[1] = a[1] * b[1]

c[2] = a[2] * b[2]

We can perform this operation directly in NumPy.

In [ ]:
# multiply vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


# Vector Division
Two vectors of equal length can be divided.


c = a / b
As with other arithmetic operations, this operation is performed element-wise to result in a new vector of the same length.

a / b = (a1 / b1, a2 / b2, a3 / b3)
or

c[0] = a[0] / b[0]

c[1] = a[1] / b[1]

c[2] = a[2] / b[2]

We can perform this operation directly in NumPy.

In [ ]:
from numpy import array
a = array([6, 8, 9])
print(a)
b = array([1, 2, 3])
print(b)
c = a / b
print(c)

[6 8 9]
[1 2 3]
[6. 4. 3.]


# Vector Dot Product
We can calculate the sum of the multiplied elements of two vectors of the same length to give a scalar.


c = a . b

The operation can be used in machine learning to calculate the weighted sum of a vector.

The dot product is calculated as follows:

a . b = (a1 * b1 + a2 * b2 + a3 * b3)


We can calculate the dot product between two vectors in Python using the dot() function on a NumPy array. It can also be calculated using the newer @ operator, since Python version 3.5. The example below demonstrates both methods.

In [ ]:
# dot product vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a.dot(b)
print(c)
d = a @ b
print(d)

[1 2 3]
[1 2 3]
14
14


# Distance from origin

In [ ]:
import numpy as np
a = np.array([5,6,7])
y = np.linalg.norm(a)
print(y)


10.488088481701515


# Vector-Scalar Multiplication
A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector.

To keep notation simple, we will use lowercase “s” to represent the scalar value.

c = s * v

or

c = sv

The multiplication is performed on each element of the vector to result in a new scaled vector of the same length.

s * v = (s * v1, s * v2, s * v3)

Or, put another way:

c[0] = a[0] * s

c[1] = a[1] * s

c[2] = a[2] * s

We can perform this operation directly with the NumPy array.

In [ ]:
# vector-scalar multiplication
from numpy import array
a = array([1, 2, 3])
print(a)
s = 0.5
print(s)
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]


# Problem statement
A vector is given by, v = 2i + j. Find the magnitude of the vector when it is scaled by a constant of 0.4.

In [ ]:
import numpy as np
v = np.array([2,1])
scaled_v = v * (0.4)
# now to find magnitude apply norm
magnitude_v = np.linalg.norm(scaled_v)
magnitude_v

0.894427190999916

Two vectors are given by, a = 2i + j + k and b = i + j + k. Find the dot product of these two vectors.

In [ ]:
a = np.array([2,1,1])
b = np.array([1,1,1])
c = a.dot(b)
c

4